spring:
  application:
    name: user-service
  profiles:
    group:
      local:
        - "mockjwt"
        - "debug"

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health, info, metadata, prometheus
  endpoint:
    health:
      show-details: when_authorized